baseURL = "http://guillaumelam.me/"
languageCode = "en-us"
title = "Guillaume Lam Portfolio"
theme = "gl-theme"

# Metadata
[params]
	author = "Guillaume Lam"
	description = "Portfolio"

# Hero section (from here on is for icon theme)
[params.hero]
	img = "images/hero_bg.jpg"
	title = "Guillaume Lam: software enthusiast"
	# description = "Lovingly hand-crafted by the fine folks at [FreeHTML5.co](http://freehtml5.co/)"
	description = "Looking for the cv? Download it [here](/cv/guillaumelam-cv.pdf)"

# Navigation section
[params.nav]
	workExperience = "Work Experience"
	projects = "Personal projects"
	aboutMe = "About Me"
	contact = "Get In Touch"
	# Include logo instead if HOME:
	# logo = "path/to/logo"

# Work Experience section
[params.workExperience]
	enable = true

	[params.workExperience.images]
		enable = true

	[[params.workExperience.images.list]]
		img = "images/img_3.jpg"
	[[params.workExperience.images.list]]
		img = "images/img_2.jpg"
#	[[params.workExperience.images.list]]
#		img = "images/img_1.jpg"
#	[[params.workExperience.images.list]]
#		img = "images/img_4.jpg"

	[[params.workExperience.item]]
		weight = 1
		name = "marketing"
		title = "Marketing"
		subtitle = "Hello me! Does this work? Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione voluptate laborum sapiente officiis molestiaea."
		description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae aliquid aperiam eveniet officia molestiae temporibus beatae dolores dignissimos aspernatur eius doloremque ad, eaque pariatur, repellendus illum, nostrum velit necessitatibus molestias.</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

	[[params.workExperience.item]]
		weight = 2
		name = "analysis"
		title = "Resources"
		subtitle = "Quam quasi illum expedita dicta nemo fugit reprehenderit similique! Corporis praesentium magnam sequi."
		description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo, molestiae eaque fugiat dolores est esse, doloremque placeat assumenda corrupti officia dolorum. Sunt saepe ut, explicabo consectetur, nostrum illo est.</p><ul class='checked'><li>Free HTML5 Templates</li><li>Free Bootstrap Templates</li><li>Free HTML5 Bootstrap Templates</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

	[[params.workExperience.item]]
		weight = 3
		name = "strategy"
		title = "Strategy"
		subtitle = "Magnam iste obcaecati illo laboriosam amet. Dignissimos sed quis voluptatum corporis adipisci amet."
		description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio dolore illum expedita placeat debitis, dignissimos obcaecati et modi. Possimus id dicta consequuntur veritatis, reiciendis at expedita voluptate sint distinctio eligendi!</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

# Projects section
[params.projects]
	enable = true
	video = true
	vidlink = "https://vimeo.com/channels/staffpicks/93951774"
	title = "Personal Projects"
	description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

	[[params.projects.item]]
		icon = "icon-present"
		title = "Web Development"
		description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
		link = "https://www.google.ca/"

	[[params.projects.item]]
		icon = "icon-eye"
		title = "Retina Ready"
		description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

	[[params.projects.item]]
		icon = "icon-paper-plane"
		title = "Light Speed"
		description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

	[[params.projects.item]]
		icon = "icon-pencil"
		title = "Copyrighting"
		description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

	[[params.projects.item]]
		icon = "icon-rocket"
		title = "Load Fast"
		description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

	[[params.projects.item]]
		icon = "icon-support"
		title = "Customer Support"
		description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

# About Me section
[params.aboutMe]
	enable = true
	title = "About Me"
	description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

	[[params.aboutMe.item]]
	    name = "Jean Doe"
	    position = "Chief legend"
	    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
	    img = "images/person1.jpg"
	    facebook = "#"
	    twitter = "#"
	    instagram = "#"
	    github = "#"
	    linkedin = "#"

	[[params.aboutMe.item]]
	    name = "Alice Doe"
	    position = "Chief overlord"
	    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
	    img = "images/person2.jpg"
	    facebook = "#"
	    twitter = "#"
	    instagram = "#"
	    github = "#"
	    linkedin = "#"

	[[params.aboutMe.item]]
	    name = "John Doe"
	    position = "Chief haranguer"
	    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
	    img = "images/person3.jpg"
	    facebook = "#"
	    twitter = "#"
	    instagram = "#"
	    github = "#"
	    linkedin = "#"

#	[[params.aboutMe.item]]
#	    name = "Jason Doe"
#	    position = "Chief haranguer"
#	    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
#	    img = "images/person3.jpg"
#	    facebook = "#"
#	    twitter = "#"
#	    instagram = "#"
#	    github = "#"

# Work section
[params.work]
	enable = true

    [[params.work.item]]
        title = "Consectetur adipisicing"
        subtitle = "Web Design"
        img = "images/img_1.jpg"

	[[params.work.item]]
		title = "Consectetur adipisicing"
		subtitle = "Web Design"
		img = "images/img_2.jpg"

	[[params.work.item]]
		title = "Consectetur adipisicing"
		subtitle = "Web Design"
		img = "images/img_3.jpg"

	[[params.work.item]]
		title = "Consectetur adipisicing"
		subtitle = "Web Design"
		img = "images/img_2.jpg"

	[[params.work.item]]
		title = "Consectetur adipisicing"
		subtitle = "Web Design"
		img = "images/img_3.jpg"

	[[params.work.item]]
		title = "Consectetur adipisicing"
		subtitle = "Web Design"
		img = "images/img_2.jpg"

	[[params.work.item]]
		title = "Consectetur adipisicing"
		subtitle = "Web Design"
		img = "images/img_3.jpg"

	[[params.work.item]]
		title = "Consectetur adipisicing"
		subtitle = "Web Design"
		img = "images/img_4.jpg"

# Contact section
[params.contact]
	enable = true
	title = "Get In Touch"
	message = "Need to send me an email? Use the section below to do so and I'll respond as soon as possible!"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
	enable = true
	note = "<p><small>&copy; 2016 Free HTML5 Template. All Rights Reserved. <br> Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a><br>Want to learn about how this was made?<br>Checkout <a href='https://gohugo.io' target='_blank'>Hugo</a> and the theme by <a href='https://themes.gohugo.io/hugo-icon/' target='_blank'>SteveLane</a></small></p>"
	github = "https://github.com/GuillaumeLam"
	linkedin = "https://www.linkedin.com/in/guillaumelam/"
#	facebook = "https://www.facebook.com/guillaume.lam.3"
#	twitter = "#"
#	instagram = "#"